# Generated by Django 3.0 on 2020-02-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='internshipopportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=30, null=True)),
                ('typeofjob', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('preferredlanguages', models.CharField(blank=True, max_length=30, null=True)),
                ('preferredtoolsandtechnologies', models.CharField(blank=True, max_length=30, null=True)),
                ('stipend', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('interviewdate', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='internshipplusplacementopportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=30, null=True)),
                ('typeofjob', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('preferredlanguages', models.CharField(blank=True, max_length=30, null=True)),
                ('preferredtoolsandtechnologies', models.CharField(blank=True, max_length=30, null=True)),
                ('package', models.PositiveIntegerField(blank=True, null=True)),
                ('stipend', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bondterm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('interviewdate', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='placementopportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(blank=True, max_length=30, null=True)),
                ('typeofjob', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('preferredlanguages', models.CharField(blank=True, max_length=30, null=True)),
                ('preferredtoolsandtechnologies', models.CharField(blank=True, max_length=30, null=True)),
                ('package', models.PositiveIntegerField(blank=True, null=True)),
                ('bondterm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('interviewdate', models.DateField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
