# Generated by Django 3.0 on 2020-02-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipplusplacementopportunity',
            name='bondterm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internshipplusplacementopportunity',
            name='package',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placementopportunity',
            name='bondterm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placementopportunity',
            name='package',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
