# Generated by Django 3.0 on 2020-03-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipopportunity',
            name='last_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internshipplusplacementopportunity',
            name='last_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placementopportunity',
            name='last_result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
