# Generated by Django 3.0 on 2020-03-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_results_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='enrollmentno',
        ),
        migrations.RemoveField(
            model_name='results',
            name='name',
        ),
        migrations.AddField(
            model_name='results',
            name='enrollmentno_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
