# Generated by Django 3.0 on 2020-04-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0010_finalresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='finalresult',
        ),
    ]
