# Generated by Django 3.0 on 2020-04-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0011_delete_finalresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encode_company', models.CharField(blank=True, max_length=100, null=True)),
                ('opp_type', models.CharField(blank=True, max_length=100, null=True)),
                ('enrollmentno', models.CharField(max_length=11)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('middlename', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('companyname', models.CharField(blank=True, max_length=30, null=True)),
                ('typeofjob', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('preferredlanguages', models.CharField(blank=True, max_length=30, null=True)),
                ('preferredtoolsandtechnologies', models.CharField(blank=True, max_length=30, null=True)),
                ('package', models.FloatField(blank=True, null=True)),
                ('stipend', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bondterm', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
