# Generated by Django 3.0 on 2020-02-19 08:57

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='completeddetails',
            fields=[
                ('enrollmentno', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('filleddetails', models.BooleanField(default=False)),
                ('internship', models.BooleanField(default=False)),
                ('placement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('enrollmentno', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('middlename', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('G', 'Female'), ('O', 'Other')], max_length=30, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phno', models.PositiveIntegerField(blank=True, null=True)),
                ('parentphno', models.PositiveIntegerField(blank=True, null=True)),
                ('program', models.TextField(blank=True, choices=[('BTECH-CSE-BDA', 'BTECH-CSE-BDA'), ('BTECH-CSE-CBA', 'BTECH-CSE-CBA'), ('BTECH-CSE-CS', 'BTECH-CSE-CS')], max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ssc_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ssc_percentage', models.FloatField(blank=True, null=True)),
                ('ssc_board', models.TextField(blank=True, choices=[('GSEB', 'GSEB'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('OTHER', 'OTHER')], null=True)),
                ('hsc_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hsc_percentage', models.FloatField(blank=True, null=True)),
                ('hsc_board', models.CharField(blank=True, choices=[('GSHEB', 'GSHEB'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('OTHER', 'OTHER')], max_length=30, null=True)),
                ('diploma_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diploma_university', models.CharField(blank=True, max_length=30, null=True)),
                ('diploma_percentage', models.FloatField(blank=True, null=True)),
                ('sgpa_sem_1', models.FloatField(blank=True, null=True)),
                ('sgpa_sem_2', models.FloatField(blank=True, null=True)),
                ('sgpa_sem_3', models.FloatField(blank=True, null=True)),
                ('sgpa_sem_4', models.FloatField(blank=True, null=True)),
                ('sgpa_sem_5', models.FloatField(blank=True, null=True)),
                ('sgpa_sem_6', models.FloatField(blank=True, null=True)),
                ('sgpa_sem_7', models.FloatField(blank=True, null=True)),
                ('sgpa_sem_8', models.FloatField(blank=True, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('cityofinterest', models.TextField(blank=True, null=True)),
                ('skillset', models.TextField(blank=True, null=True)),
                ('postionofinterest', models.TextField(blank=True, null=True)),
                ('toolsandtechnology', models.TextField(blank=True, null=True)),
                ('linkedinURL', models.URLField(blank=True, max_length=400, null=True)),
                ('effbacklog', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True)),
                ('sign', models.FileField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='postion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='placed',
            fields=[
                ('enrollmentno', models.OneToOneField(db_column='enrollmentno', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='student.details')),
            ],
        ),
    ]
