# Generated by Django 3.0 on 2020-02-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postion',
            new_name='position',
        ),
    ]
