# Generated by Django 3.0 on 2020-02-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200221_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='details',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='details',
            name='sign',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
