# Generated by Django 3.0 on 2020-02-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200222_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='sign',
            field=models.TextField(blank=True, null=True),
        ),
    ]
