# Generated by Django 3.0 on 2020-02-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200222_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encode_company', models.CharField(blank=True, max_length=100, null=True)),
                ('enrollmentno', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
    ]
