# Generated by Django 3.0 on 2020-02-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='details',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='resume'),
        ),
        migrations.AlterField(
            model_name='details',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='sign'),
        ),
    ]
