# Generated by Django 3.0 on 2020-02-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200224_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='date_ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField(blank=True, null=True)),
                ('nextday', models.DateField(blank=True, null=True)),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
