# Generated by Django 3.0 on 2020-02-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_date_ref_change_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='date_ref',
        ),
    ]
