# Generated by Django 3.0 on 2020-04-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20200409_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completeddetails',
            old_name='selectinternshipselected',
            new_name='internshipselected',
        ),
        migrations.RenameField(
            model_name='completeddetails',
            old_name='selectplacementselected',
            new_name='placementselected',
        ),
    ]
