# Generated by Django 3.0 on 2020-04-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_studentintershipdetails_studentplaceddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentintershipdetails',
            name='typeofjob',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentplaceddetails',
            name='typeofjob',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
