# Generated by Django 3.0 on 2020-04-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20200409_2134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentIntershipDetails',
        ),
        migrations.DeleteModel(
            name='studentplacedDetails',
        ),
    ]
