# Generated by Django 3.0 on 2020-04-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20200409_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentIntershipDetails',
            fields=[
                ('enrollmentno', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('companyname', models.CharField(blank=True, max_length=30, null=True)),
                ('stipend', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('typeofjob', models.CharField(blank=True, max_length=30, null=True)),
                ('encode_company', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentplacedDetails',
            fields=[
                ('enrollmentno', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('companyname', models.CharField(blank=True, max_length=30, null=True)),
                ('package', models.FloatField(blank=True, null=True)),
                ('bondterm', models.FloatField(blank=True, null=True)),
                ('typeofjob', models.CharField(blank=True, max_length=30, null=True)),
                ('encode_company', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
