# Generated by Django 3.0 on 2020-04-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_studentintershipdetails_studentplaceddetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentIntershipDetails',
            new_name='studentInternshipDetails',
        ),
    ]
