# Generated by Django 3.0 on 2020-04-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20200411_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeddetails',
            name='OfferLetterVerified',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
