# Generated by Django 3.0 on 2020-04-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_completeddetails_offerletterverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completeddetails',
            name='OfferLetterVerified',
            field=models.BooleanField(default=False),
        ),
    ]
