# Generated by Django 3.0 on 2020-04-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_completeddetails_offerlettercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeddetails',
            name='reuploadofferletter',
            field=models.BooleanField(default=False),
        ),
    ]
