# Generated by Django 3.0 on 2020-04-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_completeddetails_reuploadofferletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeddetails',
            name='reuploadofferletter',
        ),
    ]
